CREATE DATABASE IF NOT EXISTS `contacts`;

USE `contacts`;

CREATE TABLE `contact` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(75) NULL DEFAULT NULL,
    `lastName` VARCHAR(75) NULL DEFAULT NULL,
    `emailAddress` VARCHAR(50) NULL DEFAULT NULL,
    `phoneNumber` VARCHAR(12) NULL DEFAULT NULL,
    `model` VARCHAR(50) NULL DEFAULT NULL,
    `message` VARCHAR(500) NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);

CREATE DATABASE IF NOT EXISTS `cars`;

CREATE TABLE `car` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `model` VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);